plugins {
    id 'com.android.application'
}

android {
    namespace 'com.resgatenasestrelas.game'
    compileSdk 35

    defaultConfig {
        applicationId 'com.resgatenasestrelas.game'
        minSdk 24
        targetSdk 35
        versionCode 14
        versionName '2.4'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}
